interactions:
  information: "Who are we hitting?"
  render_information: false
  self:
    type: "Self"
    information: "Self Interactions apply to your own character. They do require a validation still. But the Counter roll is a Generic Die instead. This means that you are still the Engager and the DM makes the Counter Roll."
    render_information: false
    base_cost:
      build_cost: 0
      energy_cost: 0

  direct:
    type: "Direct"
    information: "Ranged Interactions include actions like using bows, guns, and boomerangs. These interactions offer an increased range compared to Direct Interactions but come with a lower success rate due to a penalty on the Engagement Roll. Additionally, the target must not be obstructed or invisible to the Engager by default."
    render_information: false
    default_range: 1
    default_targets: 1
    base_cost:
      build_cost: 0
      energy_cost: 0
    fields:
      - key: range
        label: "Range"
        type: dropdown
        default: "1"
        options:
          - value: "1"
            label: "1m (direct)"
            cost:
              build_cost: 0
          - value: "5"
            label: "5m (Close)"
            cost:
              build_cost: 0
          - value: "25"
            label: "25m (Medium)"
            cost:
              build_cost: 0
          - value: "50"
            label: "50m (Long)"
            cost:
              build_cost: 0
      - key: targets
        label: "Targets"
        type: free_number
        default: 1
        min: 1
        max: 8
        step: 1
        per_step:
          increase:
            build_cost: 0
            energy_cost: 0

  area:
    type: "Area"
    information: "Area Interactions encompass actions like bombs, splash potions, and traps. These interactions always have a defined Radius and Range. Radius determines the area where the Enactment will take effect; Range specifies how far from the user the point of origin is set."
    render_information: false
    default_radius: 1
    default_range: 5
    base_cost:
      build_cost: 0
      energy_cost: 0
    fields:
      - key: radius
        label: "Radius"
        type: free_number
        default: 1
        min: 1
        max: 6
        step: 1
        per_step:
          increase:
            build_cost: 0
            energy_cost: 0
      - key: range
        label: "Range"
        type: dropdown
        default: "1"
        options:
          - value: "1"
            label: "1m (Close)"
            cost:
              build_cost: 0
          - value: "5"
            label: "5m (Close)"
            cost:
              build_cost: 0
          - value: "25"
            label: "25m (Medium)"
            cost:
              build_cost: 0
          - value: "50"
            label: "50m (Long)"
            cost:
              build_cost: 0
      - key: area-duration
        label: "Duration (rounds)"
        type: free_number
        default: 0
        min: 0
        max: 6
        step: 1
        per_step:
          increase:
            build_cost: 0
            energy_cost: 0
          decrease:
            build_cost: 0
            energy_cost: 0

