proficiencies:
  - id: untrained
    name: "Untrained"
    cost: 1
    die: "d4"
    vitals:
      hp: 8
      movement: 3
      energy: 5
  - id: novice
    name: "Novice"
    cost: 1
    die: "d6"
    vitals:
      hp: 12
      movement: 4
      energy: 8
  - id: proficient
    name: "Proficient"
    cost: 1
    die: "d8"
    vitals:
      hp: 16
      movement: 5
      energy: 12
  - id: expert
    name: "Expert"
    cost: 1
    die: "d10"
    vitals:
      hp: 20
      movement: 6
      energy: 16
  - id: master
    name: "Master"
    cost: 1
    die: "d12"
    vitals:
      hp: 24
      movement: 7
      energy: 20
  - id: legendary
    name: "Legendary"
    cost: 0
    die: "d20"
    vitals:
      hp: 28
      movement: 8
      energy: 25
