traits:
  general:
    - Stealth
    - Perception
    - Nature
    - Crafting
    - People Skill
    - Performance
    - Thievery
    - Knowledge
    - Magic
    - Medicine
  offense:
    - Strength
    - Precision
    - Wisdom
    - Magic
  defense:
    - Constitution
    - Reflex
    - Wisdom
    - Magic
  vital:
    - HP
    - Movement
    - Energy
