proficiencies:
  - id: clumsy
    name: "Clumsy"
    cost: 1
    dice:
      general: "d4"
      offense: "d4"
      defense: "d4"
    vitals:
      hp: 8
      movement: 3
      energy: 5
  - id: untrained
    name: "Untrained"
    cost: 1
    dice:
      general: "d6"
      offense: "d6"
      defense: "d6"
    vitals:
      hp: 12
      movement: 4
      energy: 8
  - id: trained
    name: "Trained"
    cost: 1
    dice:
      general: "d8"
      offense: "d8"
      defense: "d8"
    vitals:
      hp: 16
      movement: 5
      energy: 12
  - id: expert
    name: "Expert"
    cost: 1
    dice:
      general: "d10"
      offense: "d10"
      defense: "d10"
    vitals:
      hp: 20
      movement: 6
      energy: 16
  - id: master
    name: "Master"
    cost: 1
    dice:
      general: "d12"
      offense: "d12"
      defense: "d12"
    vitals:
      hp: 24
      movement: 7
      energy: 20
  - id: banana
    name: "banana"
    cost: 1
    dice:
      general: "+3"
      offense: "+3"
      defense: "+3"
    vitals:
      hp: 26
      movement: 12
      energy: 70
  - id: legendary
    name: "Legendary"
    cost: 0
    note: "Not purchasable via standard points"
    dice:
      general: "d20"
      offense: "d20"
      defense: "d20"
    vitals:
      hp: 28
      movement: 8
      energy: 25